### ISSUE TITLE
Standards Table update

### ISSUE THREAD

**Issue by rt5v3y02fk** [Crypto-Done-Right/CryptoDoneRight#10]
## 1. DESCRIPTION
> Change the "Avoid" heading to read "Disable"

## 2. TYPE OF ISSUE

- [ ] Feedback (Good or Bad!)
- [ ] Request for Content
- [x] Error in Content
- [ ] Outdated Content
- [ ] Page Layout
- [ ] URL Linking Issue
- [ ] Code Bug (e.g. Jekyll Template)
- [ ] Other

## 3. ADDITIONAL DETAILS
> TLS 1.1 needs to move to the Disable column
Move ssh-rsa to the Disable Column

## 4. CHECK LIST

- [x] I have looked for existing issues or change requests to prevent duplicate submissions.
- [x] I have provided all of the known, relevant details within this issue.

You are now ready to submit! We look forward to your input!

**Comment by aaron-kulkarni** [comment]
Changed content
